runtime: python38 # or another supported version

instance_class: F1

env_variables:
  MYSQL_USER: 'root' # please put in your credentials
  MYSQL_PASSWORD: <placeholder> # please put in your credentials
  MYSQL_DB: 'todo' # please put in your credentials
  MYSQL_HOST: 69.206.61.33 # please put in your credentials
  MYSQL_PORT: '1560'
  MYSQL_QUERY: ''

handlers:
- url: /img
  static_dir: static/img

- url: /script
  static_dir: static/script

- url: /styles
  static_dir: static/styles